# Generated by Django 4.2.24 on 2025-09-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
