# Generated by Django 4.2.24 on 2025-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quntity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
